name: Deploy to Production environment
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: "14"
      - run: npm install
      - run: npm run build
      - name: Generate zip file
        run: |
          echo "Removing node_modules and src"
          rm -rf ./node_modules
          rm -rf ./src
          zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.APP_NAME }}
          environment_name: ${{ secrets.ENV_NAME }}
          version_label: deploy-${{ github.run_number }}
          region: ca-central-1
          deployment_package: deploy.zip
